#!/bin/bash
if [ $# -eq 0 ]
then
    git reflog | grep "checkout:" | awk '{ print $8 }' | awk '!a[$0]++' | head | nl
fi

if [ $# -eq 1 ]; then
    re='[a-zA-M]'

    if [[ "$1" == "d" ]]; then
        git checkout develop
    elif [[ "$1" == "m" ]]; then
        git checkout master
    elif [[ "$1" =~ $re ]]; then
        echo "Branches starting with $1:"
        b | grep -i --color=always "$1"
    else
        b | sed -n ${1}p | awk '{ print $2 }' | xargs git checkout
    fi
fi
