#!/bin/sh

# Show last 10 git branches we checked out.
if [ $# -eq 0 ]; then
    git reflog | grep checkout | awkc 8 | unique | head | nl
fi

# If passed a number, switch to that correspoding branch
if [ $# -eq 1 ]; then
    bl | sed -n ${1}p | awkc 2 | xargs git checkout
fi

