#!/bin/sh

# Show last 10 git branches we checked out.
if [ $# -eq 0 ]; then
    #git reflog | grep checkout | awkc 8 #| unique | head | nl
    echo test
fi

# If passed a number, switch to that correspoding branch
if [ $# -eq 1 ]; then
    re='[a-zA-M]'
    if [[ "$1" == "d" ]]; then
        git checkout develop
    elif [[ "$1" =~ $re ]]; then
        echo "Branches starting with $1:"
        b | grep -i --color=always "$1"
    else
        b | sed -n ${1}p | awkc 2 | xargs git checkout
fi
