#!/bin/bash

# Checkout and track remote branch from origin (accepts the form 'origin/branch' or just 'branch')
git fetch
branch=$(echo $1 | sed -e "s:^origin/::")
echo "git checkout -t origin/$branch"
git checkout -t origin/$1
