#!/bin/sh
# Difftool the change indicated by the passed in number that corresponds to the change number
# from the gitlog or l script.

if [ $# -eq 0 ]
    then
        git diff HEAD --color=always
fi

if [ $# -eq 1 ]
    then
        choice=$1
        pchar=p
        git log --oneline -40 | sed -n $choice$pchar | awk '{ print $1 }' | xargs ddshow 
fi


