#!/usr/local/bin/python
import random

# Spits out a d3 roll if you press enter, or you can enter what number of dice you want to roll
num_dice = 3

while True:
    try:
        num_dice = int(input("Number of dice? (default: " + str(num_dice) + ") "))
    except ValueError:
        pass

    if (num_dice < 1):
        num_dice = 3

    dice_rolls = []
    for i in range(num_dice):
        dice_rolls.append(random.randint(1, 6))

    print("d" + str(num_dice) + " roll: " + (str(dice_rolls) + " = " if len(dice_rolls) > 1 else "") + str(sum(dice_rolls)))
    print("")
