#!/bin/bash

txtline () {
    echo -n "$@" | sendemail -f "ZackFleischmanBot@gmail.com" -u "[Script]" -t "zfleischman@gmail.com" -s "smtp.gmail.com:587" -o tls=yes -xu "zackfleischmanbot@gmail.com" -xp "F0cusN33dsF0cus" > /dev/null
}

txtfile () {
    sendemail -f "ZackFleischmanBot@gmail.com" -u "[Script]" -t "zfleischman@gmail.com" -s "smtp.gmail.com:587" -o tls=yes -xu "zackfleischmanbot@gmail.com" -xp "F0cusN33dsF0cus" -o message-file="$1" > /dev/null
}

if [ $# -eq 1 ]
then
    txtline $1
else
    echo -n > /tmp/txtmessage
    while read line
    do
        echo $line >> /tmp/txtmessage
    done < "/dev/stdin"
    txtfile /tmp/txtmessage
    rm /tmp/txtmessage
fi
