#!/usr/local/bin/python
import sys
import argparse
import smtplib
from email.mime.text import MIMEText
import email.utils

# Sends an email from my Gmail account using `smtplib`
# Can read the body from standard in or as an argument.

myName = 'Zack M Fleischman'
myEmail = 'zFleischman@gmail.com'
myPasswordFile = '/Users/zack/.gmail'

parser = argparse.ArgumentParser(description='Send an email from ' + myEmail + '. Separate multiple email addresses with commas.')
parser.add_argument("-s", "--subject", help="Subject of the Email", type=str, default="")
parser.add_argument("-t", "--to", help="To Address(es) of the Email", type=str, default=myEmail)
parser.add_argument("-c", "--cc", help="CC Address(es) of the Email", type=str)
parser.add_argument("-b", "--bcc", help="BCC Address(es) of the Email", type=str)
parser.add_argument("body", nargs="?", help="Body of the Email (reads from std-in if omitted)", type=str)
args = parser.parse_args()

# Support reading from STD-IN if we don't supply a BODY
args_body = args.body
if args_body is None:
    args_body = ""
    for line in sys.stdin:
        args_body = args_body + line


def getGmailServer():
    try:
        server = smtplib.SMTP_SSL('smtp.gmail.com')
        server.ehlo()
        server.login(myEmail, getGmailPassword())
        return server
    except:
        print("Couldn't log on to gmail...")


def getGmailPassword():
    try:
        with open(myPasswordFile) as f:
            return f.readline()
    except:
        print("Couldn't get password from file: " + myPasswordFile)


def sendEmail(subject, body, to=[], cc=[], bcc=[]):
    message = MIMEText(body)
    message['From'] = email.utils.formataddr((myName, myEmail))
    message['To'] = ','.join(to)
    message['CC'] = ','.join(cc)
    message['BCC'] = ','.join(bcc)
    message['Subject'] = subject

    recipients = to + cc + bcc

    server = getGmailServer()
    server.sendmail(myEmail, recipients, message.as_string())
    server.close()

    print("TO: " + ", ".join(to))
    if (len(cc) > 0):
        print("CC: " + ", ".join(cc))
    if (len(bcc) > 0):
        print("BCC: " + ", ".join(bcc))
    print("SUBJECT: " + subject)
    print("============ BODY ==========")
    print(body)
    print("============================")


sendEmail(args.subject,
          args_body,
          args.to.split(","),
          args.cc.split(",") if args.cc is not None else [],
          args.bcc.split(",") if args.bcc is not None else [])
