#!/bin/bash

# Repeats the passed comands every second.
# Can change this with -s or -m and provide seconds/minutes
# between loop iterations.

DELAY=1

while [[ $# -gt 1 ]]
do
    key="$1"

    case $key in
        -s|--seconds)
        DELAY="$2"
        shift
        shift
        break
        ;;

        -m|--minutes)
        DELAY=$(($2 * 60))
        shift
        shift
        break
        ;;

        *)
        break 
        ;;
    esac
done

while :
do
    eval "$@"
    sleep $DELAY
done
