#!/bin/bash

DELAY=1

while [[ $# -gt 1 ]]
do
    key="$1"

    case $key in
        -d|--delay)
        DELAY="$2"
        shift
        shift
        ;;

        *)
        break 
        ;;
    esac
done

while :
do
    eval "$@"
    sleep $DELAY
done
