#!/bin/bash
myTextMessageEmailAddress="4156968432@vzwpix.com"

if [ $# -eq 1 ]
then
    email -t $myTextMessageEmailAddress -b "$1"
else
    standardInput=`cat`
    email -t $myTextMessageEmailAddress -b "$standardInput" 
fi
