#!/bin/bash
myTextMessageEmailAddress="4156968432@vzwpix.com"

if [ $# -eq 1 ]
then
    email -t $myTextMessageEmailAddress "$1"
else
    standardInput=`cat`
    email -t $myTextMessageEmailAddress "$standardInput" 
fi
