#!/bin/bash
#
# Usage: restore show|prepare|demo|snapshot

FRONT_REPO=~/repos/front

function usage {
    echo "Usage: restore show|prepare|demo|snapshot"
    echo "  - show:     Displays current setting."
    echo "  - prepare:  Configure to setup relatively empty repo"
    echo "  - demo:     Configure to setup demo repo"
    echo "  - snapshot: Configure to setup repo from snapshot at 'front/front-snapshot.json.gz'"
    exit
}

function show {
    cat $FRONT_REPO/settings/local.json | grep restore | awk '{ print $2 }' | tr -d "\""
    exit 0
}

if [ $# -eq 0 ]
then
    show
fi

if [ "$1" == "help" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ]
then
    usage
elif [ "$1" == "show" ]
then
    show
elif [ "$1" == "snapshot" ] || [ "$1" == "prepare" ] || [ "$1" == "demo" ]
then
    sed -i '' "s/\"restore\":.*$/\"restore\": \"$1\"/" $FRONT_REPO/settings/local.json
else
    usage
fi
