#!/bin/bash
# Tests if the passed in program exists. If it doesn't, it will install it.
exists $1 "echo 'The dependency $1 is not installed! Installing...';brew install $1;echo 'Done installing $1!'"
