#!/bin/bash

title="Sir, I'm finished."
msg=""

if [ $# -eq 1 ]
    then
        title=$1
fi

if [ $# -eq 2 ]
    then
        title=$1
        msg=$2
fi

growlnotify -m "$msg" -t "$title"
#say -v Vicki "$title, $msg"
