#!/bin/bash

title="Done!"

if [ $# -gt 0 ]
    then
        title=$1
fi

if [ $# -eq 2 ]
    then
        echo "Waiting $2 minutes..."
        sleepTimeMinutes=$(( 60*$2 ))
        sleep "$sleepTimeMinutes"
fi

if [ $# -eq 3 ]
    then
        echo "Waiting $2 seconds..."
        sleep "$2"
fi


terminal-notifier -title "$title" -message ''
say "$title"
