#!/bin/bash
# Use this via an alias like:
#   alias n='path/to/success-notifier $?'
#
# Use the alias like:
#   > long-running-command;n
#       or
#   > long-running-command;n 'Label'

title='Success'
returnCode=$1
if [ $returnCode -ne 0 ]
    then
        title='Failed'
fi

message=""
if [ $# -gt 1 ]
    then
        message=$2
fi

terminal-notifier -title "$title" -message "$message" 
